### ISSUE TITLE
Logica de recepcion de informacion

### ISSUE THREAD

**Issue by diegokim** [diegofk26/taller2-cliente#3]
● Descripción: Desarrollar la lógica necesaria para que el cliente reciba información de parte del servidor por medio del protocolo HTTP.
● Tipo: feature.
● Estado: new
● Prioridad: alta
● Dueño: Diego Kim

**Comment by Seba0703** [comment]
Ya lo termine, estoy haciendo un par de cosas y dentro de un rato lo subo
Al final el error q probablemente tenias era q graph.facebook.com/youtube tira siempre error, al menos cuando lo ponia en el browser me tiraba un Json con error

**Comment by Seba0703** [comment]
ahh, otra cosa, creo q hay q poner http:// siempre, pero igual voy a agregar eso asi no hay q ponerlo

**Comment by Seba0703** [comment]
Una cosa mas, hice dos actividades:
-MainActivity q es la parte de coneccion, una vez q agregaste la url te va a mandar a ...
-la segunda actvidad q es la del registro.
Si queres ver lo q responde la URL q le mandas conmenta en el mainActivity la funcion starActivity.

**Comment by Seba0703** [comment]
cualquier cosa pregunta

**Comment by diegokim** [comment]
Faltan subir algunos archivos, las carpetas de manifest y resources, creo que de ahi viene el problema que me lo baja pero no me lo deja compilar, me tira varios errores.

**Comment by Seba0703** [comment]
uhh, ahi lo subo

**Comment by diegokim** [comment]
El error era de la version del Android studio y me faltaban instalar algunas cosas del SDK

es necesario dentro del sdk manager instalar:

-SDK Api 23
-SDK tools 23.0.2

**Comment by Seba0703** [comment]
uhh, bueno, bien q encontraste el error.

**Comment by Seba0703** [comment]
Listo
