### ISSUE TITLE
Cuestiones relacionadas con git

### ISSUE THREAD

**Issue by diegokim** [diegofk26/taller2-cliente#4]
Seccion dedicada a compartir problemas tipicos y su solucion.

**Comment by diegokim** [comment]
Al tratar de hacer un pull hay varios archivos que generan problemas aun sin haber commits posibles.

*_The following untracked working tree files would be overwritten by merge:
    .gradle/2.8/taskArtifacts/cache.properties
    .gradle/2.8/taskArtifacts/cache.properties.lock
    .gradle/2.8/taskArtifacts/fileHashes.bin
    .gradle/2.8/taskArtifacts/fileSnapshots.bin
    .gradle/2.8/taskArtifacts/outputFileStates.bin
    .gradle/2.8/taskArtifacts/taskArtifacts.bin
    .idea/.name
    .idea/compiler.xml
    .idea/copyright/profiles_settings.xml
    .idea/gradle.xml
    .idea/libraries/animated_vector_drawable_23_2_1.xml
    .idea/libraries/appcompat_v7_23_2_1.xml
    .idea/libraries/design_23_2_1.xml
    .idea/libraries/recyclerview_v7_23_2_1.xml
    .idea/libraries/support_annotations_23_2_1.xml
    .idea/libraries/support_v4_23_2_1.xml
    .idea/libraries/support_vector_drawable_23_2_1.xml
    .idea/misc.xml
    .idea/modules.xml
    .idea/runConfigurations.xml
    .idea/vcs.xml
    .idea/workspace.xml
    taller2-cliente.iml
*_

Solución: 

git clean -d -fx ""
git pull

Fuente:
http://stackoverflow.com/questions/4157189/git-pull-while-ignoring-local-changes

**Comment by Seba0703** [comment]
tuviste problemas con eso???
una pregunta, esos archivos los tengo q ignorar cuando hago un push???

**Comment by diegokim** [comment]
Si si en el gitignore pone

.gradle
/local.properties
/.idea/workspace.xml
/.idea/libraries
.DS_Store
/build

Fuente: Respuesta con 600 likes
http://stackoverflow.com/questions/16736856/what-should-be-in-my-gitignore-for-an-android-studio-project

**Comment by seguijoaquin** [comment]
Para asignar responsables de cada issue, labels y/o crear milestones, a la derecha de este mismo mensaje tienen los tags

> Labels
> Milestone
> Assignee 

Si clickean en la tuerquita del costado, pueden editar y configurar el issue para personalizarlo!

**Comment by Seba0703** [comment]
Listo
